version: 2
jobs:
  build:
    docker:
      - image: ossrs/dev
    steps:
      - checkout
      - run: cd trunk && ./configure && make
  test:
    docker:
      - image: ossrs/dev
    steps:
      - checkout
      - run: cd trunk && ./configure --gcov --without-research --without-librtmp && make && bash auto/coverage.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test

