version: 2
jobs:
  build-centos7-baseline:
    docker:
      - image: ossrs/srs:dev
    steps:
      - checkout
      - run: |
          echo "Build and run SRS baseline" &&
          cd trunk && ./configure && make
  build-centos7-noasm:
    docker:
      - image: ossrs/srs:dev
    steps:
      - checkout
      - run: |
          echo "Build and run SRS without NASM or SRTP-NASM" &&
          cd trunk && ./configure --nasm=off --srtp-nasm=off && make
  build-centos7-gb28181:
    docker:
      - image: ossrs/srs:dev
    steps:
      - checkout
      - run: |
          echo "Build and run SRS with GB28181" &&
          cd trunk && ./configure --gb28181=on && make
  build-centos8-baseline:
    docker:
      - image: ossrs/srs:dev8
    steps:
      - checkout
      - run: |
          echo "Build and run SRS for CentOS8" &&
          cd trunk && ./configure && make
  build-ubuntu20-baseline:
    docker:
      - image: ossrs/srs:dev8
    steps:
      - checkout
      - run: |
          echo "Build and run SRS for Ubuntu20" &&
          cd trunk && ./configure && make
  run-utest:
    docker:
      - image: ossrs/srs:dev
    steps:
      - checkout
      - run: |
          echo "Build and run utest for SRS" &&
          cd trunk && ./configure --gb28181=on --utest=on --gcov=on && make &&
          ./objs/srs_utest && bash auto/coverage.sh
  run-regression-test:
    docker:
      - image: ossrs/srs:dev
    steps:
      - checkout
      - run: |
          echo "Build and run SRS with regression config" &&
          cd trunk && ./configure && make && ./objs/srs -c conf/regression-test.conf &&
          echo "Run srs-bench regression test" &&
          cd 3rdparty/srs-bench && make && ./objs/srs_test -test.v
workflows:
  version: 2
  build_and_test:
    jobs:
      - build-centos7-baseline
      - run-utest
      - run-regression-test
      - build-centos7-noasm
      - build-centos7-gb28181
      - build-centos8-baseline
      - build-ubuntu20-baseline
