version: 2
jobs:
  build-centos7:
    docker:
      - image: ossrs/srs:dev
    steps:
      - checkout
      - run: |
          cd trunk && ./configure && make &&
          ./configure --nasm=off --srtp-nasm=off && make clean && make &&
          ./configure --gb28181=on && make clean && make
  test:
    docker:
      - image: ossrs/srs:dev
    steps:
      - checkout
      - run: |
          cd trunk &&
          ./configure --gb28181=on --utest=on --gcov=on && make &&
          ./objs/srs_utest && bash auto/coverage.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build-centos7
      - test
