version: 2
jobs:
  build-centos7-default:
    docker:
      - image: ossrs/srs:dev
    steps:
      - checkout
      - run: cd trunk && ./configure && make
  build-centos7-noasm:
    docker:
      - image: ossrs/srs:dev
    steps:
      - checkout
      - run: cd trunk && ./configure --nasm=off --srtp-nasm=off && make
  build-centos7-gb28181:
    docker:
      - image: ossrs/srs:dev
    steps:
      - checkout
      - run: cd trunk && ./configure --gb28181=on && make
  build-ubuntu20:
    docker:
      - image: ossrs/srs:ubuntu20
    steps:
      - checkout
      - run: cd trunk && ./configure && make
  test:
    docker:
      - image: ossrs/srs:dev
    steps:
      - checkout
      - run: |
          cd trunk &&
          ./configure --gb28181=on --utest=on --gcov=on && make &&
          ./objs/srs_utest && bash auto/coverage.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build-centos7-default
      - build-centos7-noasm
      - build-centos7-gb28181
      - build-ubuntu20
      - test
