version: 2
jobs:
  build-centos7:
    docker:
      - image: ossrs/srs:dev
    steps:
      - checkout
      - run: |
          cd trunk &&
          ./configure --gb28181=off --utest=off --srtp-nasm=off && make &&
          ./configure --gb28181=on --utest=on --srtp-nasm=on && make clean && make
  build-ubuntu20:
    docker:
      - image: ossrs/srs:ubuntu20
    steps:
      - checkout
      - run: |
          cd trunk &&
          ./configure --gb28181=off --utest=off --srtp-nasm=off && make &&
          ./configure --gb28181=on --utest=on --srtp-nasm=on && make clean && make
  test:
    docker:
      - image: ossrs/srs:dev
    steps:
      - checkout
      - run: |
          cd trunk &&
          ./configure --gb28181=on --srtp-nasm=on --utest=on --gcov=on && make &&
          ./objs/srs_utest && bash auto/coverage.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build-centos7
      - build-ubuntu20
      - test
